config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  match '/users',   to: 'users#index',   via: 'get'
  get '/pedidos/emprestar/:id', to: 'pedidos#emprestar', as: 'emprestar'
  get '/pedidos/show', to: 'pedidos#show', as: 'emprestados'
  devise_for :users
  resources :pedidos
  resources :disciplinas
  root 'disciplinas#index'
  resources :cadernos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
  belongs_to :user
  has_many :cadernos, dependent: :destroy
  validates :nome, presence: true, allow_blank: false
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  before_action :set_disciplina, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /disciplinas
  # GET /disciplinas.json
  def index
    @disciplinas = Disciplina.all
  end

  # GET /disciplinas/1
  # GET /disciplinas/1.json
  def show
    @disciplinas = Disciplina.all
    @cadernos = Caderno.all
    @contador = 1
  end

  # GET /disciplinas/new
  def new
    @disciplinas = Disciplina.all
    @disciplina = current_user.disciplinas.build
  end

  # GET /disciplinas/1/edit
  def edit
    @disciplinas = Disciplina.all
  end

  # POST /disciplinas
  # POST /disciplinas.json
  def create
    @disciplinas = Disciplina.all
    @disciplina = current_user.disciplinas.build(disciplina_params)

    respond_to do |format|
      if @disciplina.save
        format.html { redirect_to @disciplina, notice: 'Disciplina foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @disciplina }
      else
        format.html { render :new }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplinas/1
  # PATCH/PUT /disciplinas/1.json
  def update
    @disciplinas = Disciplina.all
    respond_to do |format|
      if @disciplina.update(disciplina_params)
        format.html { redirect_to @disciplina, notice: 'Disciplina atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @disciplina }
      else
        format.html { render :edit }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplinas/1
  # DELETE /disciplinas/1.json
  def destroy
    @disciplina.destroy
    respond_to do |format|
      format.html { redirect_to disciplinas_url, notice: 'Disciplina foi excluida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disciplina
      @disciplina = Disciplina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disciplina_params
      params.require(:disciplina).permit(:nome)
    end
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/views/disciplinas/_form.html.erb
<%= form_with(model: disciplina, local: true, class:"form-inline") do |form| %>
  <% if disciplina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(disciplina.errors.count, "error") %> prohibited this disciplina from being saved:</h2>

      <ul>
      <% disciplina.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table class="table table-hover table-dark" style= "width: 80%; margin: 0 auto">
  <thead>
    <tr>
      <th scope ="col" colspan="3" style = "background: rgba(32,37,41,1); border-top-left-radius: 5px; border-top-right-radius: 5px" style: "text-decoration: none; color: #e5e5e5">Disciplina </th>
    </tr>
    <tr>
      <th scope="col" style = "background: rgba(32,37,41,1)">
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon1" style = "background: #b9a88e; color: black">Titulo</span>
          <%= form.text_field :nome, id: :caderno_titulo, class:"form-control" %>
        </div>
      </th>
    </tr>
  </thead>
</table>
<div class = "container text-right" style = "width: 80%; padding-top: 15px">
<%= form.submit'Enviar', class: 'btn btn-md btn-light', style:'background: rgba(32,37,41,1); color: white' %>
</div>
<% end %>

app/views/disciplinas/edit.html.erb
<%= render 'form', disciplina: @disciplina %>
<div class = "container text-right" style = "width:80%; margin: 0 auto">
<%= link_to 'Excluir', disciplina_path(@disciplina), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class:"btn btn-danger btn-sm", style: "color: white; padding: 10px; margin-top: 15px" %>
</div>

app/views/disciplinas/index.html.erb
 <p class="text-center" style = "color: #e5e5e5; color:black;font-size: 140px; margin-top:25%"><strong>Code</strong>Book</p>

app/views/disciplinas/new.html.erb
<%= render 'form', disciplina: @disciplina %>

app/views/disciplinas/show.html.erb
<table class="table table-hover table-dark" style = "width: 80%; margin: 0 auto">
<thead>
  <tr>
    <th scope ="col" colspan="3" style = "background: rgba(32,37,41,1); border-top-left-radius: 5px; border-top-right-radius: 5px">Disciplina: <%= @disciplina.nome %> (<%= link_to 'Editar', edit_disciplina_path(@disciplina), style: "text-decoration: none; color: #e5e5e5" %>) </th>
  </tr>
  <% @cadernos.each do |caderno| %>
    <% if caderno.disciplina_id == @disciplina.id %>
      <% @contador = @contador+1 %>
    <% end %>
  <% end %>
  <% if @contador == 1 %>
    <td colspan ="3">Não há cadernos cadastrados.</td>
  <%else%>
  <tr>
    <th scope="col" style = "background: rgba(32,37,41,1)">#</th>
    <th scope="col" style = "background: rgba(32,37,41,1)">Nome do caderno</th>
    <th scope="col" style = "background: rgba(32,37,41,1)">Dono</th>
  </tr>
  <%end%>
</thead>
<tbody style = "color: #e5e5e5">

  <% @contador = 1 %>
  <% @cadernos.each do |caderno| %>
    <% if caderno.disciplina_id == @disciplina.id %>
      <tr data-link="<%= caderno_path(caderno) %>">
        <th scope="row"><%= @contador %></th>
        <% @contador = @contador + 1; %>
        <td><%= caderno.titulo %></td>
        <td><%= caderno.disciplina.user.username %></td>
      </tr>
    <% end %>
  <% end %>
  <tr data-link="<%=new_caderno_path(disciplina_id: @disciplina.id) %>" >
      <th scope="row">✎</th>
      <td colspan ="2">Criar caderno</td>
  </tr>
</tbody>
</table>

<script>
$("tr[data-link]").click(function() {
  window.location = $(this).data("link")
})
</script>