config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  match '/users',   to: 'users#index',   via: 'get'
  get '/pedidos/emprestar/:id', to: 'pedidos#emprestar', as: 'emprestar'
  get '/pedidos/show', to: 'pedidos#show', as: 'emprestados'
  devise_for :users
  resources :pedidos
  resources :disciplinas
  root 'disciplinas#index'
  resources :cadernos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pedido.rb
class Pedido < ApplicationRecord
    validates_uniqueness_of :user_orig, scope: [:user_dest, :caderno_id]
  end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:destroy, :emprestar]

  def new
    @pedido = Pedido.new(pedido_params)
  end

  def index
  end
  def show
  end

  def emprestar
    @caderno = Caderno.find(@pedido.caderno_id);
    @caderno.user << User.find(@pedido.user_dest);
    @pedido.destroy
  end

  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|

      if @pedido.save
        format.html { redirect_to users_path(search: User.find(@pedido.user_dest).username), notice: 'Pedido enviado com sucesso.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :index }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_path, notice: 'Notificação removida.' }
      format.json { head :no_content }
    end
  end

    private
      # Never trust parameters from the scary internet, only allow the white list through.
      def pedido_params
        params.require(:pedido).permit(:caderno_id, :user_dest, :user_orig)
      end
      def set_pedido
        @pedido = Pedido.find(params[:id])
      end

end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/index.html.erb
<% @pedidos = Pedido.where(user_orig: current_user.id)%>

<table class="table table-hover table-dark" style = "width: 80%; margin: 0 auto">
<thead>
  <tr>
    <th scope ="col" colspan="2" style = "background: rgba(32,37,41,1); border-top-left-radius: 5px; border-top-right-radius: 5px">Notificações: <%= @pedidos.count %> </th>
  </tr>
  <% if @pedidos.count == 0 %>
    <td colspan ="3">Não há novas notificações.</td>
  <%else%>
  <tr>
    <th scope="col" style = "background: rgba(32,37,41,1)">Notificação</th>
    <th scope="col" style = "background: rgba(32,37,41,1)">Ação</th>
  </tr>
  <%end%>
</thead>
<tbody style = "color: #e5e5e5">
  <% @pedidos.each do |pedido| %>
      <tr>
        <td>O usuário <%= User.find(pedido.user_dest).username %> está pedindo seu caderno <%= Caderno.find(pedido.caderno_id).titulo %> emprestado.</td>
        <td align = "right">
          <%= link_to 'Emprestar', emprestar_path(pedido), class: 'btn btn-md btn-light', style:'color: black; background: #b9a88e; margin-right: 20px' %>
          <%= link_to 'Não emprestar', pedido_path(pedido), method: :delete, class: 'btn btn-md btn-light', style:'color: black; background: red' %>
      </td>
      </tr>
  <% end %>
</tbody>
</table>

app/views/pedidos/show.html.erb
<table class="table table-hover table-dark" style = "width: 80%; margin: 0 auto">
<thead>
  <tr>
    <th scope ="col" colspan="3" style = "background: rgba(32,37,41,1); border-top-left-radius: 5px; border-top-right-radius: 5; text-decoration: none; color: #e5e5e5"">Cadernos Emprestados</th>
  </tr>
  <% @contador = 0 %>
    <% current_user.caderno.each do |caderno| %>
      <% @contador = @contador+1 %>
  <% end %>
  <% if @contador == 0 %>
    <td colspan ="4">Não há cadernos emprestados.</td>
  <%else%>
  <tr>
    <th scope="col" style = "background: rgba(32,37,41,1)">#</th>
    <th scope="col" style = "background: rgba(32,37,41,1)">Nome do caderno</th>
    <th scope="col" style = "background: rgba(32,37,41,1)">Nome da disciplina</th>
    <th scope="col" style = "background: rgba(32,37,41,1)">Dono</th>
  </tr>
  <%end%>
</thead>
<tbody style = "color: #e5e5e5">

  <% @contador = 1 %>
  <% current_user.caderno.each do |caderno| %>
      <tr data-link="<%= caderno_path(caderno) %>">
        <th scope="row"><%= @contador %></th>
        <% @contador = @contador + 1; %>
        <td><%= caderno.titulo %></td>
        <td><%= caderno.disciplina.nome %></td>
        <td><%= caderno.disciplina.user.username %></td>
      </tr>
  <% end %>
</tbody>
</table>

<script>
$("tr[data-link]").click(function() {
  window.location = $(this).data("link")
})
</script>