config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  match '/users',   to: 'users#index',   via: 'get'
  get '/pedidos/emprestar/:id', to: 'pedidos#emprestar', as: 'emprestar'
  get '/pedidos/show', to: 'pedidos#show', as: 'emprestados'
  devise_for :users
  resources :pedidos
  resources :disciplinas
  root 'disciplinas#index'
  resources :cadernos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/caderno.rb
class Caderno < ApplicationRecord
	belongs_to :disciplina
	has_and_belongs_to_many :user
	validates :titulo, presence: true, allow_blank: false
	serialize :permitidos_id, Array
end

app/controllers/cadernos_controller.rb
class CadernosController < ApplicationController
  before_action :set_caderno, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /cadernos
  # GET /cadernos.json
  def index
    @cadernos = Caderno.all
    @disciplinas = Disciplina.all
  end

  # GET /cadernos/1
  # GET /cadernos/1.json
  def show
    @disciplinas = Disciplina.all
  end

  # GET /cadernos/new
  def new
    @caderno = Caderno.new(disciplina_id: params[:disciplina_id])
    @disciplinas = Disciplina.all
  end

  # GET /cadernos/1/edit
  def edit
    @disciplinas = Disciplina.all
  end

  # POST /cadernos
  # POST /cadernos.json
  def create
    @disciplinas = Disciplina.all
    @caderno = Caderno.new(caderno_params)

    respond_to do |format|

      if @caderno.save
        format.html { redirect_to @caderno, notice: 'Caderno foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @caderno }
      else
        format.html { render :new }
        format.json { render json: @caderno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadernos/1
  # PATCH/PUT /cadernos/1.json
  def update
    @disciplinas = Disciplina.all
    respond_to do |format|
      if @caderno.update(caderno_params)
        format.html { redirect_to @caderno, notice: 'Caderno atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @caderno }
      else
        format.html { render :edit }
        format.json { render json: @caderno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadernos/1
  # DELETE /cadernos/1.json
  def destroy
    @caderno.destroy
    respond_to do |format|
      format.html { redirect_to disciplina_path(@caderno.disciplina), notice: 'Caderno foi excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caderno
      @caderno = Caderno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caderno_params
      params.require(:caderno).permit(:titulo, :conteudo, :disciplina_id)
    end
end

app/helpers/cadernos_helper.rb
module CadernosHelper
end

app/views/cadernos/_form.html.erb
<%= form_with(model: caderno, local: true) do |form| %>
  <% if caderno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caderno.errors.count, "error") %> prohibited this caderno from being saved:</h2>

      <ul>
      <% caderno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table class="table table-hover table-dark">
    <thead>
      <tr>
        <th scope ="col" colspan="3" style = "background: rgba(32,37,41,1); border-top-left-radius: 5px; border-top-right-radius: 5px" style: "text-decoration: none; color: #e5e5e5">Novo caderno </th>
      </tr>
      <tr>
        <th scope="col" style = "background: rgba(32,37,41,1)">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1" style = "background: #b9a88e; color: black">Titulo</span>
            <%= form.text_field :titulo, id: :caderno_titulo, class:"form-control" %>
          </div>
        </th>
      </tr>
    </thead>
    <tbody style = "color: #e5e5e5">
      <tr data-link="#">
        <td>
              <%= form.cktext_area :conteudo, id: :caderno_conteudo, ckeditor: {
                language: 'pt',
                uiColor: '#b9a88e' }
              %>
        </td>
      </tr>
      <%= form.hidden_field :disciplina_id %>
      <tr data-link="#" >
        <td colspan ="2" class="text-right">
        <%= form.submit'Enviar', class: 'btn btn-md btn-light', style:'background: #b9a88e' %>
        <%= link_to 'Voltar',  disciplina_path(@caderno.disciplina), class: 'btn btn-md btn-light', style:'background: #b9a88e; color: black' %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/cadernos/edit.html.erb
<%= render 'form', caderno: @caderno %>

app/views/cadernos/index.html.erb
 <p class="text-center" style = "color: #e5e5e5; color:black;font-size: 140px; margin-top:25%"><strong>Code</strong>Book</p>

app/views/cadernos/new.html.erb
<%= render 'form', caderno: @caderno %>

app/views/cadernos/show.html.erb
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope ="col" colspan="3" style = "background: rgba(32,37,41,1); border-top-left-radius: 5px; border-top-right-radius: 5px" style: "text-decoration: none; color: #e5e5e5">Titulo: <%= @caderno.titulo %></th>
    </tr>
    <tr>
      <th scope="col" style = "background: rgba(32,37,41,1)">
        <div class="input-group">
          <div class = "conteudo rounded">
          <%= @caderno.conteudo.html_safe %>
          </div>
        </div>
      </th>
    </tr>
  </thead>
  <tbody style = "color: #e5e5e5">
    <tr data-link="#">
      <td class = "text-right">
        <% if current_user == @caderno.disciplina.user %>
      <%= link_to 'Editar', edit_caderno_path(@caderno), class: 'btn btn-md btn-light', style:'color: black; background: #b9a88e' %>
        <% end %>
      <%= link_to 'Voltar', disciplina_path(@caderno.disciplina), class: 'btn btn-md btn-light', style:'color: black; background: #b9a88e' %> <br />
      </td>
    </tr>
  </tbody>
</table>
<div class = "text-right">
<% if current_user == @caderno.disciplina.user %>
<%= link_to 'Excluir', caderno_path(@caderno), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class:"btn btn-sm btn-danger", style: "color: white; padding: 10px; margin-top: 15px" %>
<% end %>
</div>