config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  match '/users',   to: 'users#index',   via: 'get'
  get '/pedidos/emprestar/:id', to: 'pedidos#emprestar', as: 'emprestar'
  get '/pedidos/show', to: 'pedidos#show', as: 'emprestados'
  devise_for :users
  resources :pedidos
  resources :disciplinas
  root 'disciplinas#index'
  resources :cadernos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>

    </style>
    <%= favicon_link_tag 'logofinal.jpg' %>
    <title>CodeBook</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link type = "text/css" rel = "stylesheet" href = "css/bootstrap.min.css" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <div id="msgAlerts">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div id="msgAlerts">
        <%= alert %>
      </div>
    <% end %>
    <% if(user_signed_in?) %>
    <div id = "wrapper">
    <!-- navbar-->
    <nav class="navbar navbar-dark justify-content-between border border-left-0 border-dark navbar-fixed-top" style = "background: rgba(32,37,41,1)">
      <a></a>
      <% @contador = Pedido.where(user_orig: current_user.id).count %>
      <a href = <%= pedidos_path %> class="navbar-brand" style = "color: #e5e5e5; padding-left: 5%   ">Bem vindo, <%= current_user.username %>
      <% if @contador != 0 %>
      <strong>(<%= @contador %>)</strong>
      <% end %></a>
      <%= form_tag(users_path, method: 'get', class:"form-inline") do %>
        <%= text_field_tag(:search, params[:search], class:"form-control mr-sm-2", :placeholder => "Insira um usuário") %>
        <%= submit_tag("Search", class: 'btn btn-md btn-light', style:'color: black; background: #b9a88e') %>
      <% end %>
    </nav>
    <!-- sidebar -->
    <% @contador = 0 %>
    <div id = "sidebar-wrapper">
      <ul class = "sidebar-nav">
        <li><p class="navbar-brand" style = "color: #e5e5e5; padding-left: 5%   "><strong>Code</strong>Book</p></li>
          <li><%= link_to(image_tag(current_user.avatar, class:'rounded-circle'), edit_user_registration_path)%></li>
        <% Disciplina.all.each do |disciplina| %>
          <% if disciplina.user == current_user %>
            <% @contador = @contador + 1 %>
          <% end %>
        <% end %>
        <% if @contador == 0 %>
          <li><p style = "color: #e5e5e5; padding: 0; padding-bottom: 10px; padding-top: 10px; margin: 0 auto">Não há disciplinas cadastradas</p></li>
        <% end %>
        <% Disciplina.all.each do |disciplina| %>
          <% if disciplina.user == current_user %>
            <li><%= link_to disciplina.nome, disciplina %></li>
          <% end %>
        <% end %>
        <li><%= link_to 'Criar disciplina', new_disciplina_path %></li>
        <li><%= link_to 'Cadernos emprestados', emprestados_path %></li>
        <li><%= link_to('Sair', destroy_user_session_path, method: :delete) %></li>
      <li style = "margin: 0px; padding-top: 20%  ">
        <%= image_tag "logotransp.png" %>
      </li>
      </ul>
    </div>
    <!-- content -->
    <div id = "page-content-wrapper">
      <div class = "container-fluid">
        <div class = "column-lg-12">
          <%= yield %>
        </div>
      </div>
    </div>
</div>

    <% else %>
    <%= yield %>
    <% end %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  </body>
</html>